baseURL = 'https://tasteless-aucubs.vercel.app/'
theme = 'FixIt'
title = 'tasteless'
defaultContentLanguage = 'zh-cn'
languageCode = "zh-CN"
hasCJKLanguage = true
copyright = ''
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
[breadcrumb]
enable = false
sticky = false
showHome = false
[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
title = ""
weight = 1
[menu.main.params]
class = ""
draft = false
icon = "fa-solid fa-archive"
type = ""
[[menu.main]]
identifier = "tags"
parent = ""
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 2
[menu.main.params]
icon = "fa-solid fa-tags"
[params]
version = "0.3.X"
description = "This is tasteless"
keywords = ["tasteless"]
WithSiteTitle = false
DisableThemeInject = true
[params.gitInfo]
repo = "https://github.com/aucub/tasteless"
branch = "main"
dir = "content"
[params.author]
name = "secluded"
avatar = "ğŸ²"
[params.home]
[params.home.profile]
enable = false
[params.title]
typeit = false
[params.subtitle]
typeit = false
[params.footer]
enable = false
copyright = false
author = false
license = ''
[params.footer.powered]
enable = false
hugoLogo = false
themeLogo = false
[footer.siteTime]
enable = false
animate = false
[params.backToTop]
enable = false
scrollpercent = false
[params.cookieconsent]
enable = false
[params.page]
authorAvatar = true
twemoji = true
license = ''
# æ˜¯å¦æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£å†…å®¹çš„é“¾æ¥
linkToMarkdown = false
# æ˜¯å¦æ˜¾ç¤ºæŸ¥çœ‹æ–‡ç« æºç çš„é“¾æ¥
linkToSource = false
# æ˜¯å¦æ˜¾ç¤ºç¼–è¾‘æ–‡ç« çš„é“¾æ¥
linkToEdit = false
# æ˜¯å¦æ˜¾ç¤ºæŠ¥å‘Šæ–‡ç« é—®é¢˜çš„é“¾æ¥
linkToReport = false
autoBookmark = false
wordCount = true
readingTime = true
# ä»£ç é…ç½®
[params.page.code]
# æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„ç¼–è¾‘æŒ‰é’®
edit = false
# é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
maxShownLines = 9999
# ç›¸å…³å†…å®¹é…ç½®
[params.page.related]
enable = false
# èµèµè®¾ç½®
[params.page.reward]
enable = false
# æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
[params.page.share]
enable = false
[params.page.comment]
enable = false
[params.analytics]
enable = false
